basePath: /api/v1
definitions:
  github_com_josue_chalenge_golang_internal_app_api_dto.UserDTO:
    properties:
      email:
        type: string
      password:
        type: string
      phoneNumber:
        type: string
      userName:
        type: string
    type: object
  github_com_josue_chalenge_golang_internal_app_api_dto.UserLogIn:
    properties:
      password:
        type: string
      user:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: APIs to manage Users.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: User API
  version: "1.0"
paths:
  /user:
    post:
      consumes:
      - application/json
      description: Add a new User
      parameters:
      - description: user info
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_josue_chalenge_golang_internal_app_api_dto.UserDTO'
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Create new users
      tags:
      - User
  /user/login:
    post:
      consumes:
      - application/json
      description: Loging and generate token
      parameters:
      - description: user login info
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_josue_chalenge_golang_internal_app_api_dto.UserLogIn'
      responses:
        "202":
          description: Accepted
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Login
      tags:
      - User
swagger: "2.0"
